### ISSUE TITLE
Unable to obtain the CHASMplus training set

### ISSUE THREAD

**Issue by yang-arina** [KarchinLab/CHASMplus#3]
Hi! I'm unable to access the CHASMplus training set from this link: http://karchinlab.org/data/CHASMplus/formatted_training_list.txt.gz. Are there any other ways to obtain the CHASMplus training set? This is crucial for my research. Looking forward to your reply! Thank you very much!

**Comment by RachelKarchin** [comment]
Here you go. The link has changed.
https://karchinlab.org/datasets/formatted_training_llist.txt.gz

**Comment by ctokheim** [comment]
@RachelKarchin Looks like there was an extra "l" in your file path (potentially a typo). This should work: https://karchinlab.org/datasets/formatted_training_list.txt.gz

**Comment by ctokheim** [comment]
@RachelKarchin Similar issue for most of the download links for the 20/20+ and CHASMplus websites. See https://2020plus.readthedocs.io/en/latest/download.html#necessary-data-files

**Comment by yang-arina** [comment]
> @RachelKarchin Looks like there was an extra "l" in your file path (potentially a typo). This should work: https://karchinlab.org/datasets/formatted_training_list.txt.gz

I'm sorry for bother you and thank you for your patient reply! This link does work!
